# Generated by Django 3.1.7 on 2021-06-28 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TradeLoggerAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_account_name', models.CharField(max_length=255)),
                ('trading_account_description', models.TextField()),
                ('starting_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShortIronCondorTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underlying_symbol', models.CharField(max_length=255)),
                ('underlying_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('short_call_strike', models.DecimalField(decimal_places=2, max_digits=15)),
                ('short_call_delta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('long_call_strike', models.DecimalField(decimal_places=2, max_digits=15)),
                ('long_call_delta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('short_put_strike', models.DecimalField(decimal_places=2, max_digits=15)),
                ('short_put_delta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('long_put_strike', models.DecimalField(decimal_places=2, max_digits=15)),
                ('long_put_delta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('position_bid_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('position_ask_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('open_credit_received_per_contract', models.DecimalField(decimal_places=2, max_digits=15)),
                ('closing_debit_paid_per_contract', models.DecimalField(decimal_places=2, max_digits=15)),
                ('opening_position_delta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('closing_position_delta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('opening_iv', models.DecimalField(decimal_places=2, max_digits=15)),
                ('closing_iv', models.DecimalField(decimal_places=2, max_digits=15)),
                ('annual_low_iv', models.DecimalField(decimal_places=2, max_digits=15)),
                ('annual_high_iv', models.DecimalField(decimal_places=2, max_digits=15)),
                ('opening_iv_range_60_days', models.DecimalField(decimal_places=2, max_digits=15)),
                ('closing_iv_range_60_days', models.DecimalField(decimal_places=2, max_digits=15)),
                ('opening_theta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('closing_theta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('trade_open_date', models.CharField(max_length=255)),
                ('trade_close_date', models.CharField(max_length=255)),
                ('date_of_expiration', models.CharField(max_length=255)),
                ('max_profit_probability', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_loss_probability', models.DecimalField(decimal_places=2, max_digits=15)),
                ('profit_probability', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('trading_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TradeLoggerAPI.tradingaccount')),
            ],
        ),
    ]
